FROM golang:latest

RUN mkdir /study_docker
WORKDIR /study_docker

RUN go get github.com/gin-gonic/gin
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com//jinzhu/gorm
# RUN go mod init github.com/gin-gonic/gin